import { BlogPost } from '../types';

interface ProcessedDoc {
    title: string;
    subtitle: string;
    category: string;
    tags: string[];
    contentHTML: string;
    excerpt: string;
    metaDescription: string;
}

// This is a mock service. In a real application, this would make a call
// to a backend function which in turn calls the Gemini API.
export const geminiService = {
  processGoogleDoc: async (url: string): Promise<ProcessedDoc> => {
    console.log(`Processing Google Doc URL (mocked): ${url}`);
    
    // Simulate API call delay
    await new Promise(res => setTimeout(res, 1500));

    // Based on the URL, return a mock response.
    if (url.includes('marketing-doc')) {
        return {
            title: "The Ultimate Guide to Customer Retention in 2024",
            subtitle: "Strategies that work for modern SaaS businesses.",
            category: "Retention",
            tags: ["SaaS", "Growth", "Marketing"],
            contentHTML: `
                <h2>Introduction: The Leaky Bucket Problem</h2>
                <p>In the world of SaaS, customer acquisition is only half the battle. If you're not actively working to retain your customers, you're fighting a losing game. This guide dives deep into the strategies that high-growth companies are using to keep their customers happy and engaged.</p>
                <h3>1. Proactive Communication</h3>
                <p>Don't wait for your customers to run into problems. Reach out to them with helpful tips, check in on their progress, and offer support before they even know they need it.</p>
                <ul>
                    <li>Onboarding emails</li>
                    <li>Usage-based triggers</li>
                    <li>Regular check-ins</li>
                </ul>
                <h2>2. Offer Flexible Subscription Options</h2>
                <p>Sometimes, customers don't want to cancel forever. Offering options like pausing a subscription can be a game-changer for retention. It shows you understand their needs and are willing to be flexible.</p>
                <pre><code>// Example of a pause implementation
function pauseSubscription(customerId) {
  // Your API call here
  console.log(\`Pausing subscription for \${customerId}\`);
}</code></pre>
            `,
            excerpt: "In the world of SaaS, customer acquisition is only half the battle. This guide dives deep into the strategies that high-growth companies are using to keep their customers happy and engaged.",
            metaDescription: "Learn the top customer retention strategies for SaaS businesses in 2024, from proactive communication to flexible subscription options like pausing."
        };
    }

    // Default generic response
    return {
        title: "New Post from Google Docs",
        subtitle: "Automatically generated and formatted by AI.",
        category: "General",
        tags: ["Automation", "Content"],
        contentHTML: `
            <h2>Generated Content</h2>
            <p>This content was automatically generated by processing a Google Doc. The system identified headings, paragraphs, and lists to create this structured HTML output.</p>
            <h3>Key Takeaways</h3>
            <ul>
                <li>Automation saves time.</li>
                <li>AI can help structure content.</li>
                <li>This is a proof-of-concept.</li>
            </ul>
        `,
        excerpt: "This content was automatically generated by processing a Google Doc. The system identified headings, paragraphs, and lists to create this structured HTML output.",
        metaDescription: "An article generated from a Google Doc using the power of Gemini, demonstrating automated content creation for the PauseFlow blog."
    };
  },
};